version: '3.8'
services:
  database:
    container_name: policyapp_database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - '1433:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'DatabasePassword123'
    volumes:
      - policyapp-data:/var/lib/mysql/data
volumes:
  policyapp-data:
    driver: local